# Generated by Django 5.2.1 on 2025-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dowlands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='dowlands/img', verbose_name='Картинка')),
                ('url', models.URLField(verbose_name='Ссылка на бота')),
                ('title', models.CharField(max_length=2500, verbose_name='Загаловок')),
            ],
            options={
                'verbose_name': 'СКАЧАТЬ MINES',
                'verbose_name_plural': 'СКАЧАТЬ MINES',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='game/img', verbose_name='Иконка')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ИГРА MINES ЭТО',
                'verbose_name_plural': 'ИГРА MINES ЭТО',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описания')),
                ('information', models.TextField(verbose_name='Информация')),
                ('url', models.URLField(verbose_name='Ссфлка на бота')),
                ('img', models.ImageField(upload_to='general/img', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Главная информация',
                'verbose_name_plural': 'Главная информация',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='StartGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номерация')),
                ('title', models.CharField(max_length=250, verbose_name='Описание')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'КАК НАЧАТЬ ИГРАТЬ',
                'verbose_name_plural': 'КАК НАЧАТЬ ИГРАТЬ',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('junior', models.TextField(verbose_name='Стратегия для новичка')),
                ('middle', models.TextField(verbose_name='Стратегия для среднего игрока')),
                ('pro', models.TextField(verbose_name='Стратегия для профессионала')),
            ],
            options={
                'verbose_name': 'СТРАТЕГИИ ВЫИГРЫША В MINES',
                'verbose_name_plural': 'СТРАТЕГИИ ВЫИГРЫША В MINES',
            },
        ),
    ]
