# Generated by Django 5.2.1 on 2025-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dowlands_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
